name: bauer_nebenan
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider:
  flutter_secure_storage: 3.3.3
  shared_preferences: ^0.5.12+4
  geolocator: ^6.1.9
  http: ^0.12.2
  flutter_dotenv: ^2.1.0
  transparent_image:
  flutter_fadein: ^1.1.1
  animator: ^2.0.2
  delayed_display: ^1.1.0
  simple_animations: ^2.4.0
  keyboard_visibility: ^0.5.6
  confetti: ^0.5.4+1
  page_transition: ^1.1.7+3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/icons/intro/
    - assets/logo/
    - assets/loading/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 200
